# Generated by Django 5.2.4 on 2025-07-29 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='last_watched_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.video'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='progress_percent',
            field=models.FloatField(default=0.0),
        ),
    ]
