# Generated by Django 5.2.3 on 2025-07-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='special_tag',
            field=models.CharField(choices=[('top_author', 'Top Author'), ('editors_choice', "Editor's Choice"), ('none', 'None')], default='none', help_text="Special tag for the course (e.g., Top Author, Editor's Choice)", max_length=20),
        ),
    ]
