# Generated by Django 5.2.3 on 2025-07-11 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='course.course'),
            preserve_default=False,
        ),
    ]
