# Generated by Django 5.2.3 on 2025-08-06 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_enrollment_last_watched_video_and_more'),
        ('course', '0003_enrollment_is_active'),
    ]

    operations = [
    ]
