# Generated by Django 5.2.3 on 2025-08-12 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_merge_20250806_1552'),
        ('course', '0004_merge_20250807_1827'),
    ]

    operations = [
    ]
