# Generated by Django 4.2.22 on 2025-07-12 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_faq_course'),
        ('course', '0004_alter_course_special_tag'),
    ]

    operations = [
    ]
