# Generated by Django 5.2.3 on 2025-07-11 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_faq_course'),
        ('course', '0004_alter_course_special_tag'),
    ]

    operations = [
    ]
