# Generated by Django 4.2.22 on 2025-07-12 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_merge_0003_faq_course_0004_alter_course_special_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='discounted_price',
            new_name='current_price',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='price',
            new_name='old_price',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_img',
            new_name='thumbnail',
        ),
    ]
