# Generated by Django 4.2.23 on 2025-08-21 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_merge_20250812_1511'),
        ('course', '0005_merge_20250818_1456'),
    ]

    operations = [
    ]
