# Generated by Django 5.2.3 on 2025-08-29 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_merge_20250812_1511'),
        ('course', '0005_merge_20250818_1456'),
    ]

    operations = [
    ]
