# Generated by Django 4.2.22 on 2025-07-21 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_course_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='progress',
        ),
    ]
