# Generated by Django 5.2.4 on 2025-08-04 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0002_remove_batch_announcement_manager_and_more'),
        ('quiz', '0002_alter_quiz_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='batch',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='batch.batch'),
            preserve_default=False,
        ),
    ]
