# Generated by Django 5.2.3 on 2025-08-26 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0009_suspendedbatchstudent'),
        ('quiz', '0004_quiz_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='batch.batch'),
        ),
    ]
