# Generated by Django 5.2.3 on 2025-08-29 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_merge_20250829_2128'),
        ('quiz', '0004_quiz_module'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={},
        ),
        migrations.RenameField(
            model_name='quizattempt',
            old_name='attempted_on',
            new_name='attempted_at',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='module',
        ),
        migrations.RemoveField(
            model_name='quizanswer',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='mark',
        ),
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='course.course'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='passing_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
