# Generated by Django 5.2.4 on 2025-07-31 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='announcement_manager',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='batch_manager',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='content_manager',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='course_manager',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='mentors_assigned',
        ),
        migrations.AddField(
            model_name='batch',
            name='staff',
            field=models.ManyToManyField(related_name='staff_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='batch',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batchstudent',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_students', to='batch.batch'),
        ),
        migrations.AlterField(
            model_name='batchstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
