# Generated by Django 5.2.4 on 2025-08-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0002_remove_batch_announcement_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='batch_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='batchstudent',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
    ]
