# Generated by Django 5.2.3 on 2025-08-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0004_batchstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_code',
            field=models.CharField(default='null', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
