# Generated by Django 5.2.4 on 2025-08-22 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0005_alter_batch_batch_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='staff',
        ),
    ]
