# Generated by Django 5.2.4 on 2025-08-22 11:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0006_remove_batch_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='staff',
            field=models.ManyToManyField(related_name='staff_batches', through='batch.BatchStaff', to=settings.AUTH_USER_MODEL),
        ),
    ]
