# Generated by Django 5.2.4 on 2025-08-22 14:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0007_batch_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedBatch',
            fields=[
            ],
            options={
                'verbose_name': 'Archived Batch',
                'verbose_name_plural': 'Archived Batches',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('batch.batch',),
        ),
        migrations.AlterUniqueTogether(
            name='batchstudent',
            unique_together={('batch', 'student')},
        ),
    ]
