# Generated by Django 5.2.4 on 2025-08-22 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0008_archivedbatch_alter_batchstudent_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspendedBatchStudent',
            fields=[
            ],
            options={
                'verbose_name': 'Suspended Batch Student',
                'verbose_name_plural': 'Suspended Batch Students',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('batch.batchstudent',),
        ),
    ]
