# Generated by Django 4.2.23 on 2025-08-02 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_course_management_access', models.BooleanField(default=False)),
                ('has_batch_management_access', models.BooleanField(default=False)),
                ('has_content_management_access', models.BooleanField(default=False)),
                ('has_announcement_management_access', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staffprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
