# Generated by Django 4.2.22 on 2025-07-04 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneOTP',
        ),
    ]
