# Generated by Django 5.2.4 on 2025-07-22 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('course', '0006_rename_discounted_price_course_current_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(help_text='Ordering of this topic in the course')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_list', to='course.course')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('course', 'title')},
            },
        ),
    ]
