# Generated by Django 5.2.4 on 2025-08-04 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
        ('content', '0002_video_syllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='syllabus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='content.syllabus'),
        ),
    ]
