# Generated by Django 5.2.4 on 2025-08-04 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_assignment_syllabus'),
        ('batch', '0002_remove_batch_announcement_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='batch',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='batch.batch'),
            preserve_default=False,
        ),
    ]
