# Generated by Django 5.2.3 on 2025-08-21 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_assignment_created_by'),
        ('assignment', '0005_alter_assignment_batch'),
    ]

    operations = [
    ]
