# Generated by Django 5.2.4 on 2025-08-22 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_assignment_created_by'),
        ('assignment', '0005_alter_assignment_batch'),
    ]

    operations = [
    ]
