# Generated by Django 5.2.3 on 2025-08-25 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0006_merge_20250821_1106'),
        ('assignment', '0006_merge_20250821_1620'),
        ('assignment', '0006_merge_20250822_1340'),
    ]

    operations = [
    ]
